# 1. Utiliser une image Python légère
FROM python:3.12-slim

# 2. Définir le répertoire de travail   
WORKDIR /app

# 3. Copier les fichiers de l'application dans le conteneur
COPY . /app

# 4. Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# 5. Exposer le port de l'application
EXPOSE 8000 

# 6. Commande pour démarrer l'application   
